version: "3"
services:
  nodered1:
    image: nodered/node-red
    container_name: nodered1
    ports:
      - "1881:1880"
    volumes:
      - ./data1:/data
    restart: always

  nodered2:
    image: nodered/node-red
    container_name: nodered2
    ports:
      - "1882:1880"
    volumes:
      - ./data2:/data
    restart: always

  nginx-loadbalancer:
    image: nginx
    container_name: nginx-loadbalancer
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nodered1
      - nodered2
    restart: always
